USE [master]
GO

/****** Object:  Database [fashionShop]    Script Date: 1/12/2022 1:20:13 PM ******/
CREATE DATABASE [fashionShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'fashionShop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.JAGATHSTESTING\MSSQL\DATA\fashionShop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'fashionShop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.JAGATHSTESTING\MSSQL\DATA\fashionShop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [fashionShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [fashionShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [fashionShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [fashionShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [fashionShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [fashionShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [fashionShop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [fashionShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [fashionShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [fashionShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [fashionShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [fashionShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [fashionShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [fashionShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [fashionShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [fashionShop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [fashionShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [fashionShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [fashionShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [fashionShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [fashionShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [fashionShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [fashionShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [fashionShop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [fashionShop] SET  MULTI_USER 
GO

ALTER DATABASE [fashionShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [fashionShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [fashionShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [fashionShop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [fashionShop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [fashionShop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [fashionShop] SET QUERY_STORE = OFF
GO

ALTER DATABASE [fashionShop] SET  READ_WRITE 
GO

